/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeIconField: typeof import('primevue/iconfield')['default']
    PrimeInputIcon: typeof import('primevue/inputicon')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMessage: typeof import('primevue/message')['default']
    PrimeProgressSpinner: typeof import('primevue/progressspinner')['default']
    PrimeSelectButton: typeof import('primevue/selectbutton')['default']
    PrimeTag: typeof import('primevue/tag')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
